language: node_js

node_js:
- "9"

before_install:
- openssl aes-256-cbc -K $encrypted_843662992c36_key -iv $encrypted_843662992c36_iv
  -in TXRsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 111.230.174.166\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- ssh root@111.230.174.166 "sudo -i /root/gitcode/fantasy-nations.net/autoFetch.sh $TRAVIS_BRANCH"

addons:
  ssh_known_hosts: 111.230.174.166

branches:
  only: master
